"use client";
import { useMemo,useRef,useState } from "react";

type Decision="Admissible"|"Qualify"|"Blocked"|"Approval required";
type Claim={id:string;domain:string;text:string;decision:Decision;severity:"Material"|"Moderate";owner:string;reason:string;safe:string;evidence:string;span:string;scope:Record<string,string>};
const claims:Claim[]=[
{id:"CLM-042",domain:"Service levels",text:"Northstar will receive a 99.99% monthly availability commitment.",decision:"Blocked",severity:"Material",owner:"Commercial Legal",reason:"The cited 99.99% commitment belongs to a negotiated customer exception. The standard Enterprise SLA supports 99.9%; it cannot be reused without a new approval.",safe:"The standard Enterprise service commits to 99.9% monthly availability. A higher commitment would require a negotiated contractual exception.",evidence:"Enterprise SLA v3 · §2",span:"“Provider will make the Enterprise Service available 99.9% of each calendar month…”",scope:{Entity:"Proofline Systems, Inc.",Product:"Enterprise",Deployment:"SaaS",Territory:"US · Canada",Contract:"Standard MSA",Validity:"May 2026–May 2027"}},
{id:"CLM-051",domain:"Data governance",text:"Customer data is deleted within 90 days after contract termination.",decision:"Blocked",severity:"Material",owner:"Privacy",reason:"The current policy requires deletion within 30 days. The 90-day statement came from a superseded, customer-specific response.",safe:"Customer data is deleted within 30 days after termination, subject to documented legal-retention exceptions.",evidence:"Data Retention Policy v5 · §4.2",span:"“Production customer data will be deleted no later than thirty (30) days following termination…”",scope:{Entity:"All operating entities",Product:"All cloud products",Deployment:"SaaS",Territory:"Global",Contract:"Standard policy",Validity:"Mar 2026–current"}},
{id:"CLM-064",domain:"Cross-border data",text:"All North American support access occurs exclusively in the United States and Canada.",decision:"Qualify",severity:"Material",owner:"Privacy",reason:"Production locations are documented, but the subprocessor register does not resolve whether support telemetry can be accessed from Mexico.",safe:"Primary production processing occurs in the United States and Canada. Confirmation of support-access locations and transfer safeguards is pending.",evidence:"Subprocessor Register · Aug 2026",span:"“Primary production regions: United States, Canada. Support telemetry locations: under review.”",scope:{Entity:"Proofline Systems, Inc.",Product:"Enterprise",Deployment:"Multi-tenant SaaS",Territory:"US · Canada · Mexico",Contract:"Northstar RFP",Validity:"Aug–Nov 2026"}},
{id:"CLM-077",domain:"Accessibility",text:"The platform complies with every accessibility law applicable to this procurement.",decision:"Approval required",severity:"Material",owner:"Accessibility Counsel",reason:"A current conformance report supports product-level statements, but the solicitation does not resolve every governing federal, state, provincial, territorial, or contractual rule.",safe:"A current Accessibility Conformance Report is available. Applicability to prescribed requirements is subject to procurement and counsel confirmation.",evidence:"Accessibility Conformance Report · Jul 2026",span:"“Evaluation scope: Enterprise web application; conformance assessed against the criteria enumerated herein.”",scope:{Entity:"Proofline Systems, Inc.",Product:"Web application",Deployment:"Browser",Territory:"North America",Contract:"Solicitation-specific",Validity:"Jul 2026–Jul 2027"}},
{id:"CLM-083",domain:"Insurance",text:"Current insurance covers operations throughout the US, Canada, and Mexico in the requested currencies.",decision:"Blocked",severity:"Material",owner:"Finance",reason:"The certificate covers US and Canadian operations in USD. Mexican territorial scope and CAD/MXN equivalency are not evidenced.",safe:"Current evidence covers US and Canadian operations with limits stated in USD. Mexican scope and currency equivalency require carrier confirmation.",evidence:"Certificate of Insurance · Aug 2026",span:"“Territory: United States and Canada. Limits expressed in United States Dollars.”",scope:{Entity:"Proofline Systems, Inc.",Product:"Corporate coverage",Deployment:"N/A",Territory:"US · Canada",Contract:"2026 policy",Validity:"Aug 2026–Aug 2027"}},
{id:"CLM-019",domain:"Encryption",text:"Customer data is encrypted at rest using AES-256 and in transit using TLS 1.2 or higher.",decision:"Admissible",severity:"Moderate",owner:"Security",reason:"Both statements are directly supported by current global standards covering the proposed product and deployment.",safe:"Customer data is encrypted at rest using AES-256 and in transit using TLS 1.2 or higher.",evidence:"Encryption Standard v3 · §§3–4",span:"“Customer data at rest: AES-256. Data in transit: TLS 1.2 or later.”",scope:{Entity:"All operating entities",Product:"All cloud products",Deployment:"SaaS",Territory:"Global",Contract:"Security standard",Validity:"Jul 2026–Jul 2027"}}
];
const evidence=[["Enterprise SLA v3","Current","Commercial Legal","Enterprise · standard MSA","May 2027"],["Data Retention Policy v5","Current","Privacy","All cloud products · global","Current"],["Northstar RFP + Amendment 02","Controlling","Proposal Ops","Northstar · North America","Sep 2026"],["Subprocessor Register","Incomplete","Privacy","US + Canada · Mexico open","Nov 2026"],["Customer Aurora MSA","Restricted","Commercial Legal","Aurora only · no reuse","Expired"],["Accessibility Conformance Report","Current","Accessibility","Web application","Jul 2027"]];
const manifest=[["CLM-019","Encryption","Admissible","Security","2 evidence spans","Jul 2026"],["CLM-042","Service levels","Blocked","Commercial Legal","Wrong-scope source","Open"],["CLM-051","Data governance","Blocked","Privacy","Superseded source","Open"],["CLM-064","Cross-border","Qualify","Privacy","Incomplete source","Open"],["CLM-077","Accessibility","Approval required","Counsel","Current report","Open"],["CLM-083","Insurance","Blocked","Finance","Partial territory","Open"]];
function Pill({d}:{d:Decision}){return <span className={`decision decision-${d.toLowerCase().replaceAll(" ","-")}`}>{d}</span>}

export default function Home(){
 const [view,setView]=useState<"preflight"|"ledger"|"evidence"|"manifest">("preflight"),[selectedId,setSelectedId]=useState("CLM-042"),[filter,setFilter]=useState<"All"|Decision>("All"),[query,setQuery]=useState(""),[checking,setChecking]=useState(false),[toast,setToast]=useState(""),[showUpload,setShowUpload]=useState(false),[qualified,setQualified]=useState<string[]>([]); const fileInput=useRef<HTMLInputElement>(null);
 const selected=claims.find(c=>c.id===selectedId)??claims[0], effective:Decision=qualified.includes(selected.id)?"Admissible":selected.decision, blockers=11-qualified.length;
 const filtered=useMemo(()=>claims.filter(c=>(filter==="All"||c.decision===filter)&&(c.text+c.id+c.domain+c.owner).toLowerCase().includes(query.toLowerCase())),[filter,query]);
 const flash=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2500)};
 const runCheck=()=>{setChecking(true);window.setTimeout(()=>{setChecking(false);flash("Preflight complete · 11 claims still stop submission")},1200)};
 const exportManifest=()=>{const rows=[["Claim ID","Domain","Decision","Authority","Evidence","Approval"],...manifest];const csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const u=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download="northstar-submission-manifest.csv";a.click();URL.revokeObjectURL(u);flash("Submission manifest exported")};
 const applySafe=()=>{if(selected.decision!=="Qualify"){flash("Wording alone cannot clear this claim · accountable approval required");return}setQualified(v=>[...new Set([...v,selected.id])]);flash("Qualified language applied · decision recorded")};
 const nav=[["preflight","Preflight","11"],["ledger","Claim ledger","118"],["evidence","Evidence registry","24"],["manifest","Submission manifest","118"]] as const;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><span>Proofline</span></div><div className="workspace-label">Response integrity</div><nav>{nav.map(([k,l,n])=><button key={k} className={view===k?"nav-item active":"nav-item"} onClick={()=>setView(k)}><span>{l}</span><span className="nav-count">{n}</span></button>)}</nav><div className="sidebar-message"><span>◆</span><div><strong>Submission gate active</strong><small>{blockers} material claims unresolved</small></div></div><div className="sidebar-bottom"><div className="health"><span className="pulse"/><div><strong>Evidence graph current</strong><span>24 sources · policy set NA-3.4</span></div></div><div className="user"><span className="avatar">CM</span><div><strong>Chitransha Mishra</strong><span>Proposal lead</span></div></div></div></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">NORTHSTAR GROUP · ENTERPRISE VENDOR RFP</div><h1>{view==="evidence"?"Evidence registry":view==="manifest"?"Submission manifest":view==="ledger"?"Atomic claim ledger":"Pre-submission integrity check"}</h1></div><div className="top-actions"><button className="button secondary" onClick={()=>setShowUpload(true)}>New preflight</button><button className="button primary" onClick={exportManifest}>Export manifest</button></div></header>
 {(view==="preflight"||view==="ledger")&&<><section className="submission-gate"><span className="gate-icon">!</span><div><strong>Submission locked</strong><p>{blockers} material claims are blocked, qualified, or awaiting accountable approval. Proofline will not release a clean response package.</p></div><button onClick={()=>setView("manifest")}>Review gate conditions →</button></section>
 <section className="project-strip"><div className="project-file"><span className="file-glyph">XLS</span><div><strong>Northstar_Enterprise_Vendor_RFP.xlsx</strong><span>42 requirements decomposed into 118 atomic claims</span></div></div><div className="project-meta"><span>Applicability</span><strong>US · Canada · Mexico</strong></div><div className="project-meta"><span>Policy set</span><strong>NA Commercial · v3.4</strong></div><button className="check-button" onClick={runCheck} disabled={checking}><span className={checking?"spinner":"check-dot"}/>{checking?"Running preflight…":"Run preflight again"}</button></section>
 <section className="scope-strip"><div><span>Responding entity</span><strong>Proofline Systems, Inc.</strong></div><div><span>Product / tier</span><strong>Enterprise · SaaS</strong></div><div><span>Governing document</span><strong>RFP + Amendment 02</strong></div><div><span>Sector overlay</span><strong>Industry-neutral</strong></div><div className="legal-boundary"><span>Decision boundary</span><strong>Applicability routed—not guessed</strong></div></section>
 <section className="metrics-grid"><article className="metric hero-metric"><div><span className="metric-label">Claim admissibility</span><strong className="big-number">79<span>%</span></strong><p>93 of 118 claims can ship without qualification.</p></div><div className="readiness-ring"><span>79%</span></div></article><article className="metric"><span className="metric-label">Admissible</span><strong className="metric-number green">93</strong><p>Current, in-scope evidence</p></article><article className="metric"><span className="metric-label">Must qualify</span><strong className="metric-number amber">14</strong><p>Evidence supports narrower language</p></article><article className="metric"><span className="metric-label">Stops submission</span><strong className="metric-number red">{blockers}</strong><p>Blocked or accountable approval required</p></article></section>
 <section className="content-grid"><div className="queue-card"><div className="queue-header"><div><h2>Material claim interventions</h2><p>Ranked by commercial exposure—not generation confidence.</p></div><div className="search-wrap"><span>⌕</span><input aria-label="Search claims" placeholder="Search claims" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="filters">{(["All","Blocked","Qualify","Approval required","Admissible"] as const).map(v=><button key={v} className={filter===v?"filter active":"filter"} onClick={()=>setFilter(v)}>{v}<span>{v==="All"?118:claims.filter(c=>c.decision===v).length}</span></button>)}</div><div className="requirements-list">{filtered.map(c=><button key={c.id} className={selectedId===c.id?"requirement-row selected":"requirement-row"} onClick={()=>setSelectedId(c.id)}><div className="requirement-top"><span className="req-id">{c.id}</span><span className={`severity severity-${c.severity.toLowerCase()}`}>{c.severity}</span><Pill d={qualified.includes(c.id)?"Admissible":c.decision}/></div><p>{c.text}</p><div className="requirement-foot"><span>{c.domain}</span><span>Authority · {c.owner}</span></div></button>)}</div></div>
 <aside className="detail-card"><div className="detail-head"><div><span className="req-id">{selected.id}</span><h2>{selected.domain}</h2></div><Pill d={effective}/></div><p className="claim-text">“{selected.text}”</p><div className={`decision-callout decision-callout-${effective.toLowerCase().replaceAll(" ","-")}`}><strong>{effective}</strong><p>{qualified.includes(selected.id)?"Qualified wording is supported by the cited evidence and recorded scope.":selected.reason}</p></div><div className="section-heading"><span>Evidence span</span><small>{selected.evidence}</small></div><blockquote>{selected.span}</blockquote><div className="section-heading"><span>Scope carried by evidence</span><small>6 dimensions</small></div><div className="scope-grid">{Object.entries(selected.scope).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="section-heading"><span>Safe response language</span><button onClick={()=>{navigator.clipboard.writeText(selected.safe);flash("Safe language copied")}}>Copy</button></div><div className="safe-language">{selected.safe}</div><div className="authority-row"><div><span>Accountable authority</span><strong>{selected.owner}</strong></div><span className="authority-status">Decision required</span></div><div className="detail-actions"><button className="button secondary" onClick={()=>flash(`Exception routed to ${selected.owner}`)}>Route exception</button><button className="button primary" onClick={applySafe}>{qualified.includes(selected.id)?"Qualified language applied":"Apply safe language"}</button></div></aside></section></>}
 {view==="evidence"&&<section className="standalone-card"><div className="standalone-head"><div><h2>Evidence with boundaries</h2><p>Authority, scope, validity, and reuse restrictions travel with every source.</p></div><button className="button primary" onClick={()=>flash("Evidence intake opened")}>Add evidence</button></div><div className="source-table wide-table table-head"><span>Evidence</span><span>State</span><span>Authority</span><span>Admissible scope</span><span>Valid through</span></div>{evidence.map(r=><div className="source-table wide-table" key={r[0]}><strong>{r[0]}</strong><span className={`library-state ${r[1].toLowerCase()}`}>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span><span>{r[4]}</span></div>)}<div className="registry-note"><strong>Authority rule</strong><p>The governing solicitation and proposed contract determine applicability. Customer exceptions never become reusable merely because they were previously approved.</p></div></section>}
 {view==="manifest"&&<section className="standalone-card"><div className="manifest-hero"><div><span className="manifest-kicker">Release control</span><h2>Submission manifest</h2><p>A reproducible record of each material claim, supporting span, applicable scope, accountable decision, and policy version.</p></div><div className="manifest-lock"><span>LOCKED</span><strong>{blockers} gate conditions open</strong><small>Clean response package unavailable</small></div></div><div className="manifest-summary"><div><span>Response hash</span><strong>NRTH-02 · 8f2a…9c41</strong></div><div><span>Policy version</span><strong>NA Commercial · 3.4</strong></div><div><span>Evidence snapshot</span><strong>Aug 23, 2026 · 7:14 PM ET</strong></div><div><span>Reproducibility</span><strong>Deterministic decision record</strong></div></div><div className="source-table manifest-table table-head"><span>Claim</span><span>Domain</span><span>Decision</span><span>Authority</span><span>Evidence result</span><span>Approval</span></div>{manifest.map(r=><div className="source-table manifest-table" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className={`manifest-decision ${r[2].toLowerCase().replaceAll(" ","-")}`}>{r[2]}</span><span>{r[3]}</span><span>{r[4]}</span><span>{r[5]}</span></div>)}<div className="manifest-footer"><div><strong>Negative assurance is active.</strong><p>The audit manifest can be exported, but the response cannot be labeled submission-ready until material conditions are resolved.</p></div><button className="button primary" disabled>Release response package</button></div></section>}
 </main>
 {showUpload&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><button className="modal-close" onClick={()=>setShowUpload(false)}>×</button><span className="modal-kicker">New integrity preflight</span><h2>Inspect a completed response.</h2><p>Proofline decomposes proposed answers into atomic claims, binds evidence scope, and applies release gates. It does not replace your drafting workspace.</p><button className="drop-zone" onClick={()=>fileInput.current?.click()}><span className="upload-glyph">↑</span><strong>Choose completed RFP or questionnaire</strong><span>Excel, Word, CSV or PDF</span></button><input ref={fileInput} className="sr-only" type="file" onChange={e=>e.target.files?.[0]&&flash(`${e.target.files[0].name} staged for preflight`)}/><div className="demo-divider">Portfolio demo</div><button className="sample-button" onClick={()=>{setShowUpload(false);flash("Northstar preflight loaded")}}><span className="file-glyph">XLS</span><div><strong>Load Northstar response</strong><span>118 claims · 24 evidence sources · 11 gate conditions</span></div><span>→</span></button></div></div>}{toast&&<div className="toast"><span>●</span>{toast}</div>}</div>
}
