"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";

type Decision = "Admissible" | "Qualify" | "Blocked" | "Approval required";
type Upload = { file: File; role: "response" | "evidence" };
type Finding = { id:string; domain:string; claim_text:string; decision:Decision; severity:"Material"|"Moderate"|"Low"; reason:string; safe_language:string; evidence_quote:string; evidence_source:string; evidence_location:string; scope_notes:string; owner:string };
type Analysis = { response_name:string; executive_summary:string; submission_status:"Ready"|"Ready with qualifications"|"Blocked"; claims_reviewed:number; evidence_sources_reviewed:number; coverage_note:string; findings:Finding[] };

const sampleAnalysis:Analysis={response_name:"Northstar_RFP_Response.txt",executive_summary:"Proofline found five material commitments that should not reach the buyer as written. The encryption statement is supported; the SLA and retention claims conflict with controlling evidence, while data-location, accessibility and insurance language exceed the supplied scope.",submission_status:"Blocked",claims_reviewed:6,evidence_sources_reviewed:6,coverage_note:"6 material claims identified",findings:[
 {id:"CLM-001",domain:"Service levels",claim_text:"Proofline guarantees 99.99% monthly platform availability under its standard Enterprise agreement.",decision:"Blocked",severity:"Material",reason:"The standard Enterprise SLA supports 99.9%. The only 99.99% approval is explicitly restricted to another customer's negotiated agreement.",safe_language:"Proofline's standard Enterprise service commits to 99.9% monthly availability. A higher commitment would require a negotiated contractual exception.",evidence_quote:"Provider will make the Enterprise Service available 99.9% of each calendar month.",evidence_source:"Enterprise SLA v3",evidence_location:"Section 2",scope_notes:"Enterprise SaaS and the standard MSA are in scope, but the proposed percentage is not. The 99.99% exception is customer-specific and non-reusable.",owner:"Commercial Legal"},
 {id:"CLM-002",domain:"Data retention",claim_text:"All Northstar customer data will be deleted within 90 days after contract termination.",decision:"Blocked",severity:"Material",reason:"The response uses a superseded 90-day period. Current policy requires deletion no later than 30 days, subject to documented legal-retention exceptions.",safe_language:"Production customer data will be deleted no later than 30 days following termination, subject to documented legal-retention exceptions.",evidence_quote:"Production customer data will be deleted no later than thirty (30) days following termination, subject to documented legal-retention exceptions.",evidence_source:"Data Retention Policy v5",evidence_location:"Section 4.2",scope_notes:"The current policy applies globally to all cloud products and supersedes the 90-day statement.",owner:"Privacy"},
 {id:"CLM-003",domain:"Encryption",claim_text:"Customer data is encrypted at rest using AES-256 and in transit using TLS 1.2 or higher.",decision:"Admissible",severity:"Moderate",reason:"Both parts of the claim are directly supported by a current security standard with global SaaS scope.",safe_language:"Customer data is encrypted at rest using AES-256 and in transit using TLS 1.2 or higher.",evidence_quote:"Customer data at rest: AES-256. Data in transit: TLS 1.2 or later.",evidence_source:"Encryption Standard v3",evidence_location:"Sections 3–4",scope_notes:"Entity, product, deployment and territory are covered by the global cloud-product standard.",owner:"Security"},
 {id:"CLM-004",domain:"Data location",claim_text:"All production processing and support access will occur exclusively in the United States and Canada.",decision:"Qualify",severity:"Material",reason:"Production regions are supported, but support telemetry may be accessed from Mexico and remains under review.",safe_language:"Primary production processing occurs in the United States and Canada. Support-access locations and applicable transfer safeguards are subject to confirmation.",evidence_quote:"Primary production regions: United States and Canada. Support telemetry locations: under review, including potential access from Mexico.",evidence_source:"Subprocessor Register",evidence_location:"August 2026 snapshot",scope_notes:"Production location is supported; exclusive support-access geography is not.",owner:"Privacy"},
 {id:"CLM-005",domain:"Accessibility",claim_text:"The platform complies with every accessibility law applicable to this procurement across North America.",decision:"Approval required",severity:"Material",reason:"The conformance report supports a product assessment, not a universal legal-applicability conclusion for this procurement.",safe_language:"A current Accessibility Conformance Report is available for the Enterprise web application. Applicability to procurement-specific requirements requires confirmation.",evidence_quote:"Evaluation scope: Enterprise web application; conformance assessed against the criteria enumerated herein.",evidence_source:"Accessibility Conformance Report",evidence_location:"July 2026",scope_notes:"Product scope is documented; federal, state, provincial, territorial and contractual applicability is unresolved.",owner:"Accessibility Counsel"},
 {id:"CLM-006",domain:"Insurance",claim_text:"Current insurance covers operations throughout the United States, Canada, and Mexico in all requested currencies.",decision:"Blocked",severity:"Material",reason:"The certificate covers only the United States and Canada, with limits expressed in USD. Mexico and currency equivalency are not evidenced.",safe_language:"Current evidence covers operations in the United States and Canada with limits stated in USD. Mexican scope and currency equivalency require carrier confirmation.",evidence_quote:"Territory: United States and Canada. Limits expressed in United States Dollars.",evidence_source:"Certificate of Insurance",evidence_location:"August 2026",scope_notes:"Territory and currency scope do not cover the full proposed commitment.",owner:"Finance"}
]};

const accepted = ".pdf,.docx,.xlsx,.csv,.txt,.md,.json";
const decisionClass = (value:string) => value.toLowerCase().replaceAll(" ", "-");
const fileSize = (bytes:number) => bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${Math.round(bytes/1024)} KB` : `${(bytes/1048576).toFixed(1)} MB`;
const toDataUrl = (file:File) => new Promise<string>((resolve,reject) => { const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result)); reader.onerror=()=>reject(new Error(`Could not read ${file.name}`)); reader.readAsDataURL(file); });

export default function Home(){
 const [responseFile,setResponseFile]=useState<File|null>(null),[evidenceFiles,setEvidenceFiles]=useState<File[]>([]),[context,setContext]=useState("North America · industry-neutral"),[analysis,setAnalysis]=useState<Analysis|null>(null),[sampleMode,setSampleMode]=useState(false),[selected,setSelected]=useState(0),[status,setStatus]=useState<"idle"|"loading"|"error">("idle"),[error,setError]=useState("");
 const responseInput=useRef<HTMLInputElement>(null),evidenceInput=useRef<HTMLInputElement>(null);
 const selectedFinding=analysis?.findings[selected]??analysis?.findings[0];
 const totals=useMemo(()=>{const f=analysis?.findings??[];return{blocked:f.filter(x=>x.decision==="Blocked").length,qualify:f.filter(x=>x.decision==="Qualify").length,approval:f.filter(x=>x.decision==="Approval required").length,admissible:f.filter(x=>x.decision==="Admissible").length}},[analysis]);

 async function loadSample(){setError("");try{const [r,e]=await Promise.all([fetch("/samples/northstar-response.txt"),fetch("/samples/proofline-evidence-pack.txt")]);setResponseFile(new File([await r.blob()],"Northstar_RFP_Response.txt",{type:"text/plain"}));setEvidenceFiles([new File([await e.blob()],"Proofline_Evidence_Pack.txt",{type:"text/plain"})]);setContext("United States, Canada and Mexico · enterprise SaaS · industry-neutral");setSampleMode(true);setSelected(0);setAnalysis(sampleAnalysis)}catch{setError("The sample files could not be loaded. Please upload your own documents.")}}
 function onEvidence(event:ChangeEvent<HTMLInputElement>){setEvidenceFiles(Array.from(event.target.files??[]));setSampleMode(false);setAnalysis(null)}
 async function analyze(){
  if(!responseFile){setError("Add a completed RFP response first.");return} if(!evidenceFiles.length){setError("Add at least one evidence file so Proofline can verify the response.");return}
  setStatus("loading");setError("");setAnalysis(null);
  try{const uploads:Upload[]=[{file:responseFile,role:"response"},...evidenceFiles.map(file=>({file,role:"evidence" as const}))];const total=uploads.reduce((n,x)=>n+x.file.size,0);if(uploads.some(x=>x.file.size>8388608))throw new Error("Keep each file under 8 MB for this MVP.");if(total>20971520)throw new Error("Keep the combined upload under 20 MB for this MVP.");
   const files=await Promise.all(uploads.map(async({file,role})=>({role,name:file.name,mime:file.type||"application/octet-stream",data:await toDataUrl(file)})));
   const response=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({context,files})});const payload=await response.json() as Analysis&{error?:string};if(!response.ok)throw new Error(payload.error||"Analysis failed.");setSampleMode(false);setAnalysis(payload);setSelected(0);setStatus("idle")
  }catch(cause){setError(cause instanceof Error?cause.message:"Analysis failed.");setStatus("error")}
 }
 function exportReport(){if(!analysis)return;const header=["ID","Domain","Decision","Severity","Claim","Reason","Evidence source","Evidence location","Evidence quote","Safe language","Owner"],rows=analysis.findings.map(f=>[f.id,f.domain,f.decision,f.severity,f.claim_text,f.reason,f.evidence_source,f.evidence_location,f.evidence_quote,f.safe_language,f.owner]);const csv=[header,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),link=document.createElement("a");link.href=url;link.download="proofline-integrity-report.csv";link.click();URL.revokeObjectURL(url)}

 return <main className="product-shell">
  <header className="product-header"><div className="brand"><span className="brand-mark">P</span><div><strong>Proofline</strong><span>RFP response integrity agent</span></div></div><div className="header-status"><span className="live-dot"/> Working AI MVP</div></header>
  <section className="workbench"><div className="intro-row"><div><span className="eyebrow">PRE-SUBMISSION CONTROL</span><h1>Catch the claim your RFP copilot would confidently submit.</h1><p>Upload a completed response and its source evidence. Proofline uses AI to decompose material claims, test support and scope, quote the governing evidence, and block unsafe language.</p></div><button className="sample-link" onClick={loadSample}>Load planted-risk sample <span>→</span></button></div>
   <div className="setup-grid">
    <button className={`upload-card ${responseFile?"has-file":""}`} onClick={()=>responseInput.current?.click()}><span className="step">01</span><span className="upload-icon">↥</span><strong>{responseFile?responseFile.name:"Add completed RFP response"}</strong><small>{responseFile?fileSize(responseFile.size):"PDF, Word, Excel, CSV or text · up to 8 MB"}</small><span className="upload-action">{responseFile?"Replace file":"Choose response"}</span></button><input className="sr-only" ref={responseInput} type="file" accept={accepted} onChange={e=>{setResponseFile(e.target.files?.[0]??null);setSampleMode(false);setAnalysis(null)}}/>
    <button className={`upload-card ${evidenceFiles.length?"has-file":""}`} onClick={()=>evidenceInput.current?.click()}><span className="step">02</span><span className="upload-icon">⌘</span><strong>{evidenceFiles.length?`${evidenceFiles.length} evidence source${evidenceFiles.length===1?"":"s"} ready`:"Add supporting evidence"}</strong><small>{evidenceFiles.length?evidenceFiles.map(file=>file.name).join(" · "):"Policies, contracts, security docs and prior approvals"}</small><span className="upload-action">{evidenceFiles.length?"Replace evidence":"Choose evidence"}</span></button><input className="sr-only" ref={evidenceInput} type="file" multiple accept={accepted} onChange={onEvidence}/>
    <div className="run-card"><span className="step">03</span><label><span>Response context</span><input value={context} onChange={e=>setContext(e.target.value)} placeholder="Territory, product, tier, deployment…"/></label><div className="connection-status"><span className="live-dot"/><div><strong>AI analysis connected</strong><small>Securely provided by Proofline</small></div></div><small className="privacy-note">No API key required. Uploaded documents are used only to produce this analysis.</small><button className="analyze-button" onClick={analyze} disabled={status==="loading"}>{status==="loading"?<><span className="spinner"/> Inspecting claims and evidence…</>:<>Run integrity preflight <span>→</span></>}</button></div>
   </div>{error&&<div className="error-banner"><strong>Couldn’t run the preflight.</strong><span>{error}</span></div>}
  </section>
  {!analysis&&<section className="empty-state"><div className="empty-visual"><span>RESPONSE</span><i>→</i><span>EVIDENCE</span><i>→</i><strong>DECISION</strong></div><h2>This is where the useful part happens.</h2><p>Proofline does not draft another fluent answer. It shows which exact claims can ship, which need narrower language, and which must stop submission.</p><div className="capability-row"><span>Atomic claim extraction</span><span>Exact evidence quotes</span><span>Scope mismatch detection</span><span>Safe response language</span></div></section>}
  {analysis&&<section className="results"><div className="results-head"><div><span className="eyebrow">{sampleMode?"PLANTED-RISK SAMPLE":"LIVE AI ANALYSIS"} · {analysis.response_name}</span><h2>{analysis.submission_status==="Blocked"?"Submission blocked":analysis.submission_status}</h2><p>{analysis.executive_summary}</p></div><button className="export-button" onClick={exportReport}>Export audit CSV</button></div>
   <div className="metric-grid"><article><span>Claims reviewed</span><strong>{analysis.claims_reviewed}</strong><small>{analysis.coverage_note}</small></article><article className="danger"><span>Blocked</span><strong>{totals.blocked}</strong><small>Unsupported or wrong-scope</small></article><article className="warning"><span>Must qualify</span><strong>{totals.qualify}</strong><small>Narrower language supported</small></article><article><span>Approval required</span><strong>{totals.approval}</strong><small>Route to accountable owner</small></article><article className="success"><span>Admissible</span><strong>{totals.admissible}</strong><small>Supported by supplied evidence</small></article></div>
   <div className="findings-grid"><div className="finding-list"><div className="list-label"><span>Material claim interventions</span><small>{analysis.evidence_sources_reviewed} evidence sources reviewed</small></div>{analysis.findings.map((f,i)=><button key={`${f.id}-${i}`} className={`finding-row ${selected===i?"selected":""}`} onClick={()=>setSelected(i)}><div><span className="claim-id">{f.id}</span><span className={`severity ${f.severity.toLowerCase()}`}>{f.severity}</span></div><p>{f.claim_text}</p><div><span>{f.domain}</span><span className={`decision ${decisionClass(f.decision)}`}>{f.decision}</span></div></button>)}</div>
    {selectedFinding&&<aside className="finding-detail"><div className="detail-title"><div><span className="claim-id">{selectedFinding.id}</span><h3>{selectedFinding.domain}</h3></div><span className={`decision ${decisionClass(selectedFinding.decision)}`}>{selectedFinding.decision}</span></div><blockquote>“{selectedFinding.claim_text}”</blockquote><div className={`decision-box ${decisionClass(selectedFinding.decision)}`}><strong>Why</strong><p>{selectedFinding.reason}</p></div><div className="detail-section"><div><strong>Evidence used</strong><span>{selectedFinding.evidence_source} · {selectedFinding.evidence_location}</span></div><blockquote className="evidence-quote">“{selectedFinding.evidence_quote}”</blockquote></div><div className="detail-section"><strong>Scope check</strong><p>{selectedFinding.scope_notes}</p></div><div className="safe-box"><div><strong>Safe response language</strong><button onClick={()=>navigator.clipboard.writeText(selectedFinding.safe_language)}>Copy</button></div><p>{selectedFinding.safe_language}</p></div><div className="owner-row"><span>Accountable owner</span><strong>{selectedFinding.owner}</strong></div></aside>}
   </div><p className="legal-note">Proofline evaluates evidentiary support and scope. It does not make legal-compliance determinations.</p>
  </section>}
 </main>
}
